### ISSUE TITLE
How to find rare word in any document text

### ISSUE THREAD

**Issue by pribadihcr** [timoschick/bertram#2]
Hi @timoschick ,

Can we find/define some rare word in a document based on pretrained bertram?

**Comment by timoschick** [comment]
While there is no direct method to do so, each BERTRAM model requires a `.vocab` file (named `input_processor.json.vocab` for the pretrained models) which stores word frequencies for BERTRAM's training corpus. You could simply consider each word that either does not occur in this file or occurs in this file with a count less than 100 as being rare.
